services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin_bundle_listener_command:
        class: AdminBundle\EventListener\PrePersistCommand
        tags:
         - { name: doctrine.event_listener, event: prePersist}

    admin_command_manager:
        class: AdminBundle\Manager\CommandManager
        arguments: ['@doctrine.orm.entity_manager','@workflow.registry']







