<?php

namespace AppBundle\Repository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
  /*
   *   public function findAllCards($player_id)
    {
        $queryBuilder = $this->createQueryBuilder('c')
                             ->leftJoin('c.player','p')
                             ->addSelect('p')
                             ->where('p.id = :player_id')
                             ->setParameters(['id' =>$player_id]);
        return $queryBuilder->getQuery()
                            ->getResult();
    }*/
}
