<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Player;

/**
 * CardRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Player $player
     *
     * @return array
     */
    public function getListCardDashboard(Player $player)
    {
        $queryBuilder = $this->createQueryBuilder('card')
            ->leftJoin('card.score', 'score')
            ->leftJoin('score.games', 'games')
            ->select('SUM(score.result) AS sumscore')
            ->addSelect('card.number')
            ->addSelect('card.id')
            ->addSelect('card.status')
            ->addSelect('COUNT(score.result) AS nbgames')
            ->groupBy('card.number')
            ->where('card.player = :player')
            ->andWhere("(games.id is NULL OR games.booking = '0')")
//            ->orWhere("(games.id is not NULL AND games.booking = '1')")
            ->setParameters([
                'player' => $player,
            ]);
//        dump($queryBuilder->getQuery()->getResult());
//        die;
        return $queryBuilder->getQuery()->getResult();
    }
}
