<?php

namespace AppBundle\Repository;

/**
 * EtablishmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablishmentRepository extends \Doctrine\ORM\EntityRepository
{
}
