services:
    _defaults:
        autowire: true
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    player_manager:
        class: UserBundle\Manager\PlayerManager
        public: true

    avatar_upload_listener:
        class: UserBundle\DoctrineListener\AvatarUploadListener
        arguments: ['%kernel.project_dir%']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
