services:
    _defaults:
        autowire: true
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    UserBundle\Manager\PlayerManager:
        public: true

    UserBundle\DoctrineListener\AvatarUploadListener:
        public: true
        arguments: ['%kernel.project_dir%']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
