services:
    _defaults:
        autowire: true
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    UserBundle\Manager\PlayerManager:
        public: true

    UserBundle\EventSubscriber\AvatarUploadSubscriber:
        public: true
        arguments: ['%kernel.project_dir%']
        tags:
            - { name: doctrine.event_subscriber, event: prePersist}

    UserBundle\EventListener\PrePersistPlayerListener:
        public: true
        tags:
            - { name: doctrine.event_listener, event: prePersist}

    UserBundle\Manager\MailManager:
        public: true
        arguments: ['@mailer', '%mail_admin%','@templating.engine.twig']

    UserBundle\Manager\AuthenticateService:
        public: true

    UserBundle\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }